// ifc_IFC4X3_ADD2_generated_enum.cs Copyright (c) 2020, Bernhard Simon Bock, Friedrich Eder, MIT License (see https://github.com/IfcSharp/IfcSharpLibrary/blob/master/License.md)
// ported from IFC-Model by buildingSMART International Ltd (see https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/IFC4X3_ADD2.exp)
// official documentation see https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html

// CAUTION! THIS IS GENERATED CODE! DON'T MODIFY THIS FILE. THIS FILE WILL BE UPDATED WITH NEW VERSIONS.
using System;
using System.Collections.Generic;
namespace ifc{//########################################################################################################

//documentation link see end of line
[ifcSql(TypeGroupId:4,TypeId:430274,TableId:4,LayerId:10)] public enum ActionRequestTypeEnum                {EMAIL=1, FAX=2, PHONE=3, POST=4, VERBAL=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcActionRequestTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430275,TableId:4,LayerId:20)] public enum ActionSourceTypeEnum                 {BRAKES=1, BUOYANCY=2, COMPLETION_G1=3, CREEP=4, CURRENT=5, DEAD_LOAD_G=6, EARTHQUAKE_E=7, ERECTION=8, FIRE=9, ICE=10, IMPACT=11, IMPULSE=12, LACK_OF_FIT=13, LIVE_LOAD_Q=14, PRESTRESSING_P=15, PROPPING=16, RAIN=17, SETTLEMENT_U=18, SHRINKAGE=19, SNOW_S=20, SYSTEM_IMPERFECTION=21, TEMPERATURE_T=22, TRANSPORT=23, WAVE=24, WIND_W=25, USERDEFINED=26, NOTDEFINED=27, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcActionSourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430276,TableId:4,LayerId:20)] public enum ActionTypeEnum                       {EXTRAORDINARY_A=1, PERMANENT_G=2, VARIABLE_Q=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcActionTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430277,TableId:4,LayerId:12)] public enum ActuatorTypeEnum                     {ELECTRICACTUATOR=1, HANDOPERATEDACTUATOR=2, HYDRAULICACTUATOR=3, PNEUMATICACTUATOR=4, THERMOSTATICACTUATOR=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcActuatorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430278,TableId:4,LayerId:22)] public enum AddressTypeEnum                      {DISTRIBUTIONPOINT=1, HOME=2, OFFICE=3, SITE=4, USERDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAddressTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430279,TableId:4,LayerId:15)] public enum AirTerminalBoxTypeEnum               {CONSTANTFLOW=1, VARIABLEFLOWPRESSUREDEPENDANT=2, VARIABLEFLOWPRESSUREINDEPENDANT=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAirTerminalBoxTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430280,TableId:4,LayerId:15)] public enum AirTerminalTypeEnum                  {DIFFUSER=1, GRILLE=2, LOUVRE=3, REGISTER=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAirTerminalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430281,TableId:4,LayerId:15)] public enum AirToAirHeatRecoveryTypeEnum         {FIXEDPLATECOUNTERFLOWEXCHANGER=1, FIXEDPLATECROSSFLOWEXCHANGER=2, FIXEDPLATEPARALLELFLOWEXCHANGER=3, HEATPIPE=4, ROTARYWHEEL=5, RUNAROUNDCOILLOOP=6, THERMOSIPHONCOILTYPEHEATEXCHANGERS=7, THERMOSIPHONSEALEDTUBEHEATEXCHANGERS=8, TWINTOWERENTHALPYRECOVERYLOOPS=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAirToAirHeatRecoveryTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430282,TableId:4,LayerId:12)] public enum AlarmTypeEnum                        {BELL=1, BREAKGLASSBUTTON=2, LIGHT=3, MANUALPULLBOX=4, RAILWAYCROCODILE=5, RAILWAYDETONATOR=6, SIREN=7, WHISTLE=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAlarmTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430283,TableId:4,LayerId:28)] public enum AlignmentCantSegmentTypeEnum         {BLOSSCURVE=1, CONSTANTCANT=2, COSINECURVE=3, HELMERTCURVE=4, LINEARTRANSITION=5, SINECURVE=6, VIENNESEBEND=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAlignmentCantSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430284,TableId:4,LayerId:28)] public enum AlignmentHorizontalSegmentTypeEnum   {BLOSSCURVE=1, CIRCULARARC=2, CLOTHOID=3, COSINECURVE=4, CUBIC=5, HELMERTCURVE=6, LINE=7, SINECURVE=8, VIENNESEBEND=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAlignmentHorizontalSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430285,TableId:4,LayerId: 4)] public enum AlignmentTypeEnum                    {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAlignmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430286,TableId:4,LayerId:28)] public enum AlignmentVerticalSegmentTypeEnum     {CIRCULARARC=1, CLOTHOID=2, CONSTANTGRADIENT=3, PARABOLICARC=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAlignmentVerticalSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430287,TableId:4,LayerId:20)] public enum AnalysisModelTypeEnum                {IN_PLANE_LOADING_2D=1, LOADING_3D=2, OUT_PLANE_LOADING_2D=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAnalysisModelTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430288,TableId:4,LayerId:20)] public enum AnalysisTheoryTypeEnum               {FIRST_ORDER_THEORY=1, FULL_NONLINEAR_THEORY=2, SECOND_ORDER_THEORY=3, THIRD_ORDER_THEORY=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAnalysisTheoryTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430289,TableId:4,LayerId: 9)] public enum AnnotationTypeEnum                   {CONTOURLINE=1, DIMENSION=2, ISOBAR=3, ISOLUX=4, ISOTHERM=5, LEADER=6, SURVEY=7, SYMBOL=8, TEXT=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAnnotationTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430290,TableId:4,LayerId:25)] public enum ArithmeticOperatorEnum               {ADD=1, DIVIDE=2, MODULO=3, MULTIPLY=4, SUBTRACT=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcArithmeticOperatorEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430291,TableId:4,LayerId: 4)] public enum AssemblyPlaceEnum                    {FACTORY=1, SITE=2, NOTDEFINED=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAssemblyPlaceEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430292,TableId:4,LayerId:14)] public enum AudioVisualApplianceTypeEnum         {AMPLIFIER=1, CAMERA=2, COMMUNICATIONTERMINAL=3, DISPLAY=4, MICROPHONE=5, PLAYER=6, PROJECTOR=7, RECEIVER=8, RECORDINGEQUIPMENT=9, SPEAKER=10, SWITCHER=11, TELEPHONE=12, TUNER=13, USERDEFINED=14, NOTDEFINED=15, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcAudioVisualApplianceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430293,TableId:4,LayerId:30)] public enum BSplineCurveForm                     {CIRCULAR_ARC=1, ELLIPTIC_ARC=2, HYPERBOLIC_ARC=3, PARABOLIC_ARC=4, POLYLINE_FORM=5, UNSPECIFIED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBSplineCurveForm.htm
[ifcSql(TypeGroupId:4,TypeId:430294,TableId:4,LayerId:30)] public enum BSplineSurfaceForm                   {CONICAL_SURF=1, CYLINDRICAL_SURF=2, GENERALISED_CONE=3, PLANE_SURF=4, QUADRIC_SURF=5, RULED_SURF=6, SPHERICAL_SURF=7, SURF_OF_LINEAR_EXTRUSION=8, SURF_OF_REVOLUTION=9, TOROIDAL_SURF=10, UNSPECIFIED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBSplineSurfaceForm.htm
[ifcSql(TypeGroupId:4,TypeId:430295,TableId:4,LayerId: 5)] public enum BeamTypeEnum                         {BEAM=1, CORNICE=2, DIAPHRAGM=3, EDGEBEAM=4, GIRDER_SEGMENT=5, HATSTONE=6, HOLLOWCORE=7, JOIST=8, LINTEL=9, PIERCAP=10, SPANDREL=11, T_BEAM=12, USERDEFINED=13, NOTDEFINED=14, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBeamTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430296,TableId:4,LayerId: 5)] public enum BearingTypeEnum                      {CYLINDRICAL=1, DISK=2, ELASTOMERIC=3, GUIDE=4, POT=5, ROCKER=6, ROLLER=7, SPHERICAL=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBearingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430297,TableId:4,LayerId:24)] public enum BenchmarkEnum                        {EQUALTO=1, GREATERTHAN=2, GREATERTHANOREQUALTO=3, INCLUDEDIN=4, INCLUDES=5, LESSTHAN=6, LESSTHANOREQUALTO=7, NOTEQUALTO=8, NOTINCLUDEDIN=9, NOTINCLUDES=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBenchmarkEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430298,TableId:4,LayerId:15)] public enum BoilerTypeEnum                       {STEAM=1, WATER=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBoilerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430299,TableId:4,LayerId:29)] public enum BooleanOperator                      {DIFFERENCE=1, INTERSECTION=2, UNION=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBooleanOperator.htm
[ifcSql(TypeGroupId:4,TypeId:430300,TableId:4,LayerId: 4)] public enum BridgePartTypeEnum                   {ABUTMENT=1, DECK=2, DECK_SEGMENT=3, FOUNDATION=4, PIER=5, PIER_SEGMENT=6, PYLON=7, SUBSTRUCTURE=8, SUPERSTRUCTURE=9, SURFACESTRUCTURE=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBridgePartTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430301,TableId:4,LayerId: 4)] public enum BridgeTypeEnum                       {ARCHED=1, CABLE_STAYED=2, CANTILEVER=3, CULVERT=4, FRAMEWORK=5, GIRDER=6, SUSPENSION=7, TRUSS=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBridgeTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430302,TableId:4,LayerId: 7)] public enum BuildingElementPartTypeEnum          {APRON=1, ARMOURUNIT=2, INSULATION=3, PRECASTPANEL=4, SAFETYCAGE=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBuildingElementPartTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430303,TableId:4,LayerId: 5)] public enum BuildingElementProxyTypeEnum         {COMPLEX=1, ELEMENT=2, PARTIAL=3, PROVISIONFORSPACE=4, PROVISIONFORVOID=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBuildingElementProxyTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430304,TableId:4,LayerId: 5)] public enum BuildingSystemTypeEnum               {FENESTRATION=1, FOUNDATION=2, LOADBEARING=3, OUTERSHELL=4, SHADING=5, TRANSPORT=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBuildingSystemTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430305,TableId:4,LayerId: 9)] public enum BuiltSystemTypeEnum                  {EROSIONPREVENTION=1, FENESTRATION=2, FOUNDATION=3, LOADBEARING=4, MOORING=5, OUTERSHELL=6, PRESTRESSING=7, RAILWAYLINE=8, RAILWAYTRACK=9, REINFORCING=10, SHADING=11, TRACKCIRCUIT=12, TRANSPORT=13, USERDEFINED=14, NOTDEFINED=15, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBuiltSystemTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430306,TableId:4,LayerId:15)] public enum BurnerTypeEnum                       {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcBurnerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430307,TableId:4,LayerId:14)] public enum CableCarrierFittingTypeEnum          {BEND=1, CONNECTOR=2, CROSS=3, JUNCTION=4, REDUCER=5, TEE=6, TRANSITION=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCableCarrierFittingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430308,TableId:4,LayerId:14)] public enum CableCarrierSegmentTypeEnum          {CABLEBRACKET=1, CABLELADDERSEGMENT=2, CABLETRAYSEGMENT=3, CABLETRUNKINGSEGMENT=4, CATENARYWIRE=5, CONDUITSEGMENT=6, DROPPER=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCableCarrierSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430309,TableId:4,LayerId:14)] public enum CableFittingTypeEnum                 {CONNECTOR=1, ENTRY=2, EXIT=3, FANOUT=4, JUNCTION=5, TRANSITION=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCableFittingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430310,TableId:4,LayerId:14)] public enum CableSegmentTypeEnum                 {BUSBARSEGMENT=1, CABLESEGMENT=2, CONDUCTORSEGMENT=3, CONTACTWIRESEGMENT=4, CORESEGMENT=5, FIBERSEGMENT=6, FIBERTUBE=7, OPTICALCABLESEGMENT=8, STITCHWIRE=9, WIREPAIRSEGMENT=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCableSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430311,TableId:4,LayerId: 5)] public enum CaissonFoundationTypeEnum            {CAISSON=1, WELL=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCaissonFoundationTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430312,TableId:4,LayerId:42)] public enum ChangeActionEnum                     {ADDED=1, DELETED=2, MODIFIED=3, NOCHANGE=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcChangeActionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430313,TableId:4,LayerId:15)] public enum ChillerTypeEnum                      {AIRCOOLED=1, HEATRECOVERY=2, WATERCOOLED=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcChillerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430314,TableId:4,LayerId: 5)] public enum ChimneyTypeEnum                      {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcChimneyTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430315,TableId:4,LayerId:15)] public enum CoilTypeEnum                         {DXCOOLINGCOIL=1, ELECTRICHEATINGCOIL=2, GASHEATINGCOIL=3, HYDRONICCOIL=4, STEAMHEATINGCOIL=5, WATERCOOLINGCOIL=6, WATERHEATINGCOIL=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCoilTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430316,TableId:4,LayerId: 5)] public enum ColumnTypeEnum                       {COLUMN=1, PIERSTEM=2, PIERSTEM_SEGMENT=3, PILASTER=4, STANDCOLUMN=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcColumnTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430317,TableId:4,LayerId:14)] public enum CommunicationsApplianceTypeEnum      {ANTENNA=1, AUTOMATON=2, COMPUTER=3, FAX=4, GATEWAY=5, INTELLIGENTPERIPHERAL=6, IPNETWORKEQUIPMENT=7, LINESIDEELECTRONICUNIT=8, MODEM=9, NETWORKAPPLIANCE=10, NETWORKBRIDGE=11, NETWORKHUB=12, OPTICALLINETERMINAL=13, OPTICALNETWORKUNIT=14, PRINTER=15, RADIOBLOCKCENTER=16, REPEATER=17, ROUTER=18, SCANNER=19, TELECOMMAND=20, TELEPHONYEXCHANGE=21, TRANSITIONCOMPONENT=22, TRANSPONDER=23, TRANSPORTEQUIPMENT=24, USERDEFINED=25, NOTDEFINED=26, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCommunicationsApplianceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430318,TableId:4,LayerId: 2)] public enum ComplexPropertyTemplateTypeEnum      {P_COMPLEX=1, Q_COMPLEX=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcComplexPropertyTemplateTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430319,TableId:4,LayerId:15)] public enum CompressorTypeEnum                   {BOOSTER=1, DYNAMIC=2, HERMETIC=3, OPENTYPE=4, RECIPROCATING=5, ROLLINGPISTON=6, ROTARY=7, ROTARYVANE=8, SCROLL=9, SEMIHERMETIC=10, SINGLESCREW=11, SINGLESTAGE=12, TROCHOIDAL=13, TWINSCREW=14, WELDEDSHELLHERMETIC=15, USERDEFINED=16, NOTDEFINED=17, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCompressorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430320,TableId:4,LayerId:15)] public enum CondenserTypeEnum                    {AIRCOOLED=1, EVAPORATIVECOOLED=2, WATERCOOLED=3, WATERCOOLEDBRAZEDPLATE=4, WATERCOOLEDSHELLCOIL=5, WATERCOOLEDSHELLTUBE=6, WATERCOOLEDTUBEINTUBE=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCondenserTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430321,TableId:4,LayerId: 5)] public enum ConnectionTypeEnum                   {ATEND=1, ATPATH=2, ATSTART=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcConnectionTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430322,TableId:4,LayerId:24)] public enum ConstraintEnum                       {ADVISORY=1, HARD=2, SOFT=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcConstraintEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430323,TableId:4,LayerId:13)] public enum ConstructionEquipmentResourceTypeEnum{DEMOLISHING=1, EARTHMOVING=2, ERECTING=3, HEATING=4, LIGHTING=5, PAVING=6, PUMPING=7, TRANSPORTING=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcConstructionEquipmentResourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430324,TableId:4,LayerId:13)] public enum ConstructionMaterialResourceTypeEnum {AGGREGATES=1, CONCRETE=2, DRYWALL=3, FUEL=4, GYPSUM=5, MASONRY=6, METAL=7, PLASTIC=8, WOOD=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcConstructionMaterialResourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430325,TableId:4,LayerId:13)] public enum ConstructionProductResourceTypeEnum  {ASSEMBLY=1, FORMWORK=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcConstructionProductResourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430326,TableId:4,LayerId:12)] public enum ControllerTypeEnum                   {FLOATING=1, MULTIPOSITION=2, PROGRAMMABLE=3, PROPORTIONAL=4, TWOPOSITION=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcControllerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430327,TableId:4,LayerId:17)] public enum ConveyorSegmentTypeEnum              {BELTCONVEYOR=1, BUCKETCONVEYOR=2, CHUTECONVEYOR=3, SCREWCONVEYOR=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcConveyorSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430328,TableId:4,LayerId:15)] public enum CooledBeamTypeEnum                   {ACTIVE=1, PASSIVE=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCooledBeamTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430329,TableId:4,LayerId:15)] public enum CoolingTowerTypeEnum                 {MECHANICALFORCEDDRAFT=1, MECHANICALINDUCEDDRAFT=2, NATURALDRAFT=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCoolingTowerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430330,TableId:4,LayerId:10)] public enum CostItemTypeEnum                     {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCostItemTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430331,TableId:4,LayerId:10)] public enum CostScheduleTypeEnum                 {BUDGET=1, COSTPLAN=2, ESTIMATE=3, PRICEDBILLOFQUANTITIES=4, SCHEDULEOFRATES=5, TENDER=6, UNPRICEDBILLOFQUANTITIES=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCostScheduleTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430332,TableId:4,LayerId: 9)] public enum CourseTypeEnum                       {ARMOUR=1, BALLASTBED=2, CORE=3, FILTER=4, PAVEMENT=5, PROTECTION=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCourseTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430333,TableId:4,LayerId: 5)] public enum CoveringTypeEnum                     {CEILING=1, CLADDING=2, COPING=3, FLOORING=4, INSULATION=5, MEMBRANE=6, MOLDING=7, ROOFING=8, SKIRTINGBOARD=9, SLEEVING=10, TOPPING=11, WRAPPING=12, USERDEFINED=13, NOTDEFINED=14, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCoveringTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430334,TableId:4,LayerId:13)] public enum CrewResourceTypeEnum                 {OFFICE=1, SITE=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCrewResourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430335,TableId:4,LayerId: 5)] public enum CurtainWallTypeEnum                  {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCurtainWallTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430336,TableId:4,LayerId:37)] public enum CurveInterpolationEnum               {LINEAR=1, LOG_LINEAR=2, LOG_LOG=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcCurveInterpolationEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430337,TableId:4,LayerId:15)] public enum DamperTypeEnum                       {BACKDRAFTDAMPER=1, BALANCINGDAMPER=2, BLASTDAMPER=3, CONTROLDAMPER=4, FIREDAMPER=5, FIRESMOKEDAMPER=6, FUMEHOODEXHAUST=7, GRAVITYDAMPER=8, GRAVITYRELIEFDAMPER=9, RELIEFDAMPER=10, SMOKEDAMPER=11, USERDEFINED=12, NOTDEFINED=13, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDamperTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430338,TableId:4,LayerId:26)] public enum DataOriginEnum                       {MEASURED=1, PREDICTED=2, SIMULATED=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDataOriginEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430339,TableId:4,LayerId:32)] public enum DerivedUnitEnum                      {ACCELERATIONUNIT=1, ANGULARVELOCITYUNIT=2, AREADENSITYUNIT=3, COMPOUNDPLANEANGLEUNIT=4, CURVATUREUNIT=5, DYNAMICVISCOSITYUNIT=6, HEATFLUXDENSITYUNIT=7, HEATINGVALUEUNIT=8, INTEGERCOUNTRATEUNIT=9, IONCONCENTRATIONUNIT=10, ISOTHERMALMOISTURECAPACITYUNIT=11, KINEMATICVISCOSITYUNIT=12, LINEARFORCEUNIT=13, LINEARMOMENTUNIT=14, LINEARSTIFFNESSUNIT=15, LINEARVELOCITYUNIT=16, LUMINOUSINTENSITYDISTRIBUTIONUNIT=17, MASSDENSITYUNIT=18, MASSFLOWRATEUNIT=19, MASSPERLENGTHUNIT=20, MODULUSOFELASTICITYUNIT=21, MODULUSOFLINEARSUBGRADEREACTIONUNIT=22, MODULUSOFROTATIONALSUBGRADEREACTIONUNIT=23, MODULUSOFSUBGRADEREACTIONUNIT=24, MOISTUREDIFFUSIVITYUNIT=25, MOLECULARWEIGHTUNIT=26, MOMENTOFINERTIAUNIT=27, PHUNIT=28, PLANARFORCEUNIT=29, ROTATIONALFREQUENCYUNIT=30, ROTATIONALMASSUNIT=31, ROTATIONALSTIFFNESSUNIT=32, SECTIONAREAINTEGRALUNIT=33, SECTIONMODULUSUNIT=34, SHEARMODULUSUNIT=35, SOUNDPOWERLEVELUNIT=36, SOUNDPOWERUNIT=37, SOUNDPRESSURELEVELUNIT=38, SOUNDPRESSUREUNIT=39, SPECIFICHEATCAPACITYUNIT=40, TEMPERATUREGRADIENTUNIT=41, TEMPERATURERATEOFCHANGEUNIT=42, THERMALADMITTANCEUNIT=43, THERMALCONDUCTANCEUNIT=44, THERMALEXPANSIONCOEFFICIENTUNIT=45, THERMALRESISTANCEUNIT=46, THERMALTRANSMITTANCEUNIT=47, TORQUEUNIT=48, VAPORPERMEABILITYUNIT=49, VOLUMETRICFLOWRATEUNIT=50, WARPINGCONSTANTUNIT=51, WARPINGMOMENTUNIT=52, USERDEFINED=53, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDerivedUnitEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430340,TableId:4,LayerId:31)] public enum DirectionSenseEnum                   {NEGATIVE=1, POSITIVE=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDirectionSenseEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430341,TableId:4,LayerId: 7)] public enum DiscreteAccessoryTypeEnum            {ANCHORPLATE=1, BIRDPROTECTION=2, BRACKET=3, CABLEARRANGER=4, ELASTIC_CUSHION=5, EXPANSION_JOINT_DEVICE=6, FILLER=7, FLASHING=8, INSULATOR=9, LOCK=10, PANEL_STRENGTHENING=11, POINTMACHINEMOUNTINGDEVICE=12, POINT_MACHINE_LOCKING_DEVICE=13, RAILBRACE=14, RAILPAD=15, RAIL_LUBRICATION=16, RAIL_MECHANICAL_EQUIPMENT=17, SHOE=18, SLIDINGCHAIR=19, SOUNDABSORPTION=20, TENSIONINGEQUIPMENT=21, USERDEFINED=22, NOTDEFINED=23, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDiscreteAccessoryTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430342,TableId:4,LayerId:18)] public enum DistributionBoardTypeEnum            {CONSUMERUNIT=1, DISPATCHINGBOARD=2, DISTRIBUTIONBOARD=3, DISTRIBUTIONFRAME=4, MOTORCONTROLCENTRE=5, SWITCHBOARD=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDistributionBoardTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430343,TableId:4,LayerId: 6)] public enum DistributionChamberElementTypeEnum   {FORMEDDUCT=1, INSPECTIONCHAMBER=2, INSPECTIONPIT=3, MANHOLE=4, METERCHAMBER=5, SUMP=6, TRENCH=7, VALVECHAMBER=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDistributionChamberElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430344,TableId:4,LayerId: 6)] public enum DistributionPortTypeEnum             {CABLE=1, CABLECARRIER=2, DUCT=3, PIPE=4, WIRELESS=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDistributionPortTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430345,TableId:4,LayerId: 6)] public enum DistributionSystemEnum               {AIRCONDITIONING=1, AUDIOVISUAL=2, CATENARY_SYSTEM=3, CHEMICAL=4, CHILLEDWATER=5, COMMUNICATION=6, COMPRESSEDAIR=7, CONDENSERWATER=8, CONTROL=9, CONVEYING=10, DATA=11, DISPOSAL=12, DOMESTICCOLDWATER=13, DOMESTICHOTWATER=14, DRAINAGE=15, EARTHING=16, ELECTRICAL=17, ELECTROACOUSTIC=18, EXHAUST=19, FIREPROTECTION=20, FIXEDTRANSMISSIONNETWORK=21, FUEL=22, GAS=23, HAZARDOUS=24, HEATING=25, LIGHTING=26, LIGHTNINGPROTECTION=27, MOBILENETWORK=28, MONITORINGSYSTEM=29, MUNICIPALSOLIDWASTE=30, OIL=31, OPERATIONAL=32, OPERATIONALTELEPHONYSYSTEM=33, OVERHEAD_CONTACTLINE_SYSTEM=34, POWERGENERATION=35, RAINWATER=36, REFRIGERATION=37, RETURN_CIRCUIT=38, SECURITY=39, SEWAGE=40, SIGNAL=41, STORMWATER=42, TELEPHONE=43, TV=44, VACUUM=45, VENT=46, VENTILATION=47, WASTEWATER=48, WATERSUPPLY=49, USERDEFINED=50, NOTDEFINED=51, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDistributionSystemEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430346,TableId:4,LayerId:27)] public enum DocumentConfidentialityEnum          {CONFIDENTIAL=1, PERSONAL=2, PUBLIC=3, RESTRICTED=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDocumentConfidentialityEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430347,TableId:4,LayerId:27)] public enum DocumentStatusEnum                   {DRAFT=1, FINAL=2, FINALDRAFT=3, REVISION=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDocumentStatusEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430348,TableId:4,LayerId:11)] public enum DoorPanelOperationEnum               {DOUBLE_ACTING=1, FIXEDPANEL=2, FOLDING=3, REVOLVING=4, ROLLINGUP=5, SLIDING=6, SWINGING=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDoorPanelOperationEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430349,TableId:4,LayerId:11)] public enum DoorPanelPositionEnum                {LEFT=1, MIDDLE=2, RIGHT=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDoorPanelPositionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430350,TableId:4,LayerId: 5)] public enum DoorTypeEnum                         {BOOM_BARRIER=1, DOOR=2, GATE=3, TRAPDOOR=4, TURNSTILE=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDoorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430351,TableId:4,LayerId: 5)] public enum DoorTypeOperationEnum                {DOUBLE_DOOR_DOUBLE_SWING=1, DOUBLE_DOOR_FOLDING=2, DOUBLE_DOOR_LIFTING_VERTICAL=3, DOUBLE_DOOR_SINGLE_SWING=4, DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_LEFT=5, DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_RIGHT=6, DOUBLE_DOOR_SLIDING=7, DOUBLE_SWING_LEFT=8, DOUBLE_SWING_RIGHT=9, FOLDING_TO_LEFT=10, FOLDING_TO_RIGHT=11, LIFTING_HORIZONTAL=12, LIFTING_VERTICAL_LEFT=13, LIFTING_VERTICAL_RIGHT=14, REVOLVING=15, REVOLVING_VERTICAL=16, ROLLINGUP=17, SINGLE_SWING_LEFT=18, SINGLE_SWING_RIGHT=19, SLIDING_TO_LEFT=20, SLIDING_TO_RIGHT=21, SWING_FIXED_LEFT=22, SWING_FIXED_RIGHT=23, USERDEFINED=24, NOTDEFINED=25, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDoorTypeOperationEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430352,TableId:4,LayerId:15)] public enum DuctFittingTypeEnum                  {BEND=1, CONNECTOR=2, ENTRY=3, EXIT=4, JUNCTION=5, OBSTRUCTION=6, TRANSITION=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDuctFittingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430353,TableId:4,LayerId:15)] public enum DuctSegmentTypeEnum                  {FLEXIBLESEGMENT=1, RIGIDSEGMENT=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDuctSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430354,TableId:4,LayerId:15)] public enum DuctSilencerTypeEnum                 {FLATOVAL=1, RECTANGULAR=2, ROUND=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcDuctSilencerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430355,TableId:4,LayerId: 9)] public enum EarthworksCutTypeEnum                {BASE_EXCAVATION=1, CUT=2, DREDGING=3, EXCAVATION=4, OVEREXCAVATION=5, PAVEMENTMILLING=6, STEPEXCAVATION=7, TOPSOILREMOVAL=8, TRENCH=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEarthworksCutTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430356,TableId:4,LayerId: 9)] public enum EarthworksFillTypeEnum               {BACKFILL=1, COUNTERWEIGHT=2, EMBANKMENT=3, SLOPEFILL=4, SUBGRADE=5, SUBGRADEBED=6, TRANSITIONSECTION=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEarthworksFillTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430357,TableId:4,LayerId:14)] public enum ElectricApplianceTypeEnum            {DISHWASHER=1, ELECTRICCOOKER=2, FREESTANDINGELECTRICHEATER=3, FREESTANDINGFAN=4, FREESTANDINGWATERCOOLER=5, FREESTANDINGWATERHEATER=6, FREEZER=7, FRIDGE_FREEZER=8, HANDDRYER=9, KITCHENMACHINE=10, MICROWAVE=11, PHOTOCOPIER=12, REFRIGERATOR=13, TUMBLEDRYER=14, VENDINGMACHINE=15, WASHINGMACHINE=16, USERDEFINED=17, NOTDEFINED=18, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricApplianceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430358,TableId:4,LayerId:14)] public enum ElectricDistributionBoardTypeEnum    {CONSUMERUNIT=1, DISTRIBUTIONBOARD=2, MOTORCONTROLCENTRE=3, SWITCHBOARD=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricDistributionBoardTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430359,TableId:4,LayerId:14)] public enum ElectricFlowStorageDeviceTypeEnum    {BATTERY=1, CAPACITOR=2, CAPACITORBANK=3, COMPENSATOR=4, HARMONICFILTER=5, INDUCTOR=6, INDUCTORBANK=7, RECHARGER=8, UPS=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricFlowStorageDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430360,TableId:4,LayerId:18)] public enum ElectricFlowTreatmentDeviceTypeEnum  {ELECTRONICFILTER=1, USERDEFINED=2, NOTDEFINED=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricFlowTreatmentDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430361,TableId:4,LayerId:14)] public enum ElectricGeneratorTypeEnum            {CHP=1, ENGINEGENERATOR=2, STANDALONE=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricGeneratorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430362,TableId:4,LayerId:14)] public enum ElectricMotorTypeEnum                {DC=1, INDUCTION=2, POLYPHASE=3, RELUCTANCESYNCHRONOUS=4, SYNCHRONOUS=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricMotorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430363,TableId:4,LayerId:14)] public enum ElectricTimeControlTypeEnum          {RELAY=1, TIMECLOCK=2, TIMEDELAY=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElectricTimeControlTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430364,TableId:4,LayerId: 4)] public enum ElementAssemblyTypeEnum              {ABUTMENT=1, ACCESSORY_ASSEMBLY=2, ARCH=3, BEAM_GRID=4, BRACED_FRAME=5, CROSS_BRACING=6, DECK=7, DILATATIONPANEL=8, ENTRANCEWORKS=9, GIRDER=10, GRID=11, MAST=12, PIER=13, PYLON=14, RAIL_MECHANICAL_EQUIPMENT_ASSEMBLY=15, REINFORCEMENT_UNIT=16, RIGID_FRAME=17, SHELTER=18, SIGNALASSEMBLY=19, SLAB_FIELD=20, SUMPBUSTER=21, SUPPORTINGASSEMBLY=22, SUSPENSIONASSEMBLY=23, TRACKPANEL=24, TRACTION_SWITCHING_ASSEMBLY=25, TRAFFIC_CALMING_DEVICE=26, TRUSS=27, TURNOUTPANEL=28, USERDEFINED=29, NOTDEFINED=30, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElementAssemblyTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430365,TableId:4,LayerId: 4)] public enum ElementCompositionEnum               {COMPLEX=1, ELEMENT=2, PARTIAL=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcElementCompositionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430366,TableId:4,LayerId:15)] public enum EngineTypeEnum                       {EXTERNALCOMBUSTION=1, INTERNALCOMBUSTION=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEngineTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430367,TableId:4,LayerId:15)] public enum EvaporativeCoolerTypeEnum            {DIRECTEVAPORATIVEAIRWASHER=1, DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER=2, DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER=3, DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER=4, DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER=5, INDIRECTDIRECTCOMBINATION=6, INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER=7, INDIRECTEVAPORATIVEPACKAGEAIRCOOLER=8, INDIRECTEVAPORATIVEWETCOIL=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEvaporativeCoolerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430368,TableId:4,LayerId:15)] public enum EvaporatorTypeEnum                   {DIRECTEXPANSION=1, DIRECTEXPANSIONBRAZEDPLATE=2, DIRECTEXPANSIONSHELLANDTUBE=3, DIRECTEXPANSIONTUBEINTUBE=4, FLOODEDSHELLANDTUBE=5, SHELLANDCOIL=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEvaporatorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430369,TableId:4,LayerId: 3)] public enum EventTriggerTypeEnum                 {EVENTCOMPLEX=1, EVENTMESSAGE=2, EVENTRULE=3, EVENTTIME=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEventTriggerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430370,TableId:4,LayerId: 3)] public enum EventTypeEnum                        {ENDEVENT=1, INTERMEDIATEEVENT=2, STARTEVENT=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcEventTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430371,TableId:4,LayerId: 4)] public enum ExternalSpatialElementTypeEnum       {EXTERNAL=1, EXTERNAL_EARTH=2, EXTERNAL_FIRE=3, EXTERNAL_WATER=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcExternalSpatialElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430372,TableId:4,LayerId: 9)] public enum FacilityPartCommonTypeEnum           {ABOVEGROUND=1, BELOWGROUND=2, JUNCTION=3, LEVELCROSSING=4, SEGMENT=5, SUBSTRUCTURE=6, SUPERSTRUCTURE=7, TERMINAL=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFacilityPartCommonTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430373,TableId:4,LayerId: 9)] public enum FacilityUsageEnum                    {LATERAL=1, LONGITUDINAL=2, REGION=3, VERTICAL=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFacilityUsageEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430374,TableId:4,LayerId:15)] public enum FanTypeEnum                          {CENTRIFUGALAIRFOIL=1, CENTRIFUGALBACKWARDINCLINEDCURVED=2, CENTRIFUGALFORWARDCURVED=3, CENTRIFUGALRADIAL=4, PROPELLORAXIAL=5, TUBEAXIAL=6, VANEAXIAL=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFanTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430375,TableId:4,LayerId: 7)] public enum FastenerTypeEnum                     {GLUE=1, MORTAR=2, WELD=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFastenerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430376,TableId:4,LayerId:15)] public enum FilterTypeEnum                       {AIRPARTICLEFILTER=1, COMPRESSEDAIRFILTER=2, ODORFILTER=3, OILFILTER=4, STRAINER=5, WATERFILTER=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFilterTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430377,TableId:4,LayerId:16)] public enum FireSuppressionTerminalTypeEnum      {BREECHINGINLET=1, FIREHYDRANT=2, FIREMONITOR=3, HOSEREEL=4, SPRINKLER=5, SPRINKLERDEFLECTOR=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFireSuppressionTerminalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430378,TableId:4,LayerId: 6)] public enum FlowDirectionEnum                    {SINK=1, SOURCE=2, SOURCEANDSINK=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFlowDirectionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430379,TableId:4,LayerId:12)] public enum FlowInstrumentTypeEnum               {AMMETER=1, COMBINED=2, FREQUENCYMETER=3, PHASEANGLEMETER=4, POWERFACTORMETER=5, PRESSUREGAUGE=6, THERMOMETER=7, VOLTMETER=8, VOLTMETER_PEAK=9, VOLTMETER_RMS=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFlowInstrumentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430380,TableId:4,LayerId:15)] public enum FlowMeterTypeEnum                    {ENERGYMETER=1, GASMETER=2, OILMETER=3, WATERMETER=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFlowMeterTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430381,TableId:4,LayerId:21)] public enum FootingTypeEnum                      {CAISSON_FOUNDATION=1, FOOTING_BEAM=2, PAD_FOOTING=3, PILE_CAP=4, STRIP_FOOTING=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFootingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430382,TableId:4,LayerId: 8)] public enum FurnitureTypeEnum                    {BED=1, CHAIR=2, DESK=3, FILECABINET=4, SHELF=5, SOFA=6, TABLE=7, TECHNICALCABINET=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcFurnitureTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430383,TableId:4,LayerId: 4)] public enum GeographicElementTypeEnum            {SOIL_BORING_POINT=1, TERRAIN=2, VEGETATION=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcGeographicElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430384,TableId:4,LayerId:39)] public enum GeometricProjectionEnum              {ELEVATION_VIEW=1, GRAPH_VIEW=2, MODEL_VIEW=3, PLAN_VIEW=4, REFLECTED_PLAN_VIEW=5, SECTION_VIEW=6, SKETCH_VIEW=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcGeometricProjectionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430385,TableId:4,LayerId: 9)] public enum GeotechnicalStratumTypeEnum          {SOLID=1, VOID=2, WATER=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcGeotechnicalStratumTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430386,TableId:4,LayerId:39)] public enum GlobalOrLocalEnum                    {GLOBAL_COORDS=1, LOCAL_COORDS=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcGlobalOrLocalEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430387,TableId:4,LayerId: 4)] public enum GridTypeEnum                         {IRREGULAR=1, RADIAL=2, RECTANGULAR=3, TRIANGULAR=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcGridTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430388,TableId:4,LayerId:15)] public enum HeatExchangerTypeEnum                {PLATE=1, SHELLANDTUBE=2, TURNOUTHEATING=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcHeatExchangerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430389,TableId:4,LayerId:15)] public enum HumidifierTypeEnum                   {ADIABATICAIRWASHER=1, ADIABATICATOMIZING=2, ADIABATICCOMPRESSEDAIRNOZZLE=3, ADIABATICPAN=4, ADIABATICRIGIDMEDIA=5, ADIABATICULTRASONIC=6, ADIABATICWETTEDELEMENT=7, ASSISTEDBUTANE=8, ASSISTEDELECTRIC=9, ASSISTEDNATURALGAS=10, ASSISTEDPROPANE=11, ASSISTEDSTEAM=12, STEAMINJECTION=13, USERDEFINED=14, NOTDEFINED=15, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcHumidifierTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430390,TableId:4,LayerId:16)] public enum ImpactProtectionDeviceTypeEnum       {BUMPER=1, CRASHCUSHION=2, DAMPINGSYSTEM=3, FENDER=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcImpactProtectionDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430391,TableId:4,LayerId: 4)] public enum InterceptorTypeEnum                  {CYCLONIC=1, GREASE=2, OIL=3, PETROL=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcInterceptorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430392,TableId:4,LayerId: 8)] public enum InternalOrExternalEnum               {EXTERNAL=1, EXTERNAL_EARTH=2, EXTERNAL_FIRE=3, EXTERNAL_WATER=4, INTERNAL=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcInternalOrExternalEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430393,TableId:4,LayerId:14)] public enum InventoryTypeEnum                    {ASSETINVENTORY=1, FURNITUREINVENTORY=2, SPACEINVENTORY=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcInventoryTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430394,TableId:4,LayerId:14)] public enum JunctionBoxTypeEnum                  {DATA=1, POWER=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcJunctionBoxTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430395,TableId:4,LayerId:13)] public enum KerbTypeEnum                         {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcKerbTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430396,TableId:4,LayerId:30)] public enum KnotType                             {PIECEWISE_BEZIER_KNOTS=1, QUASI_UNIFORM_KNOTS=2, UNIFORM_KNOTS=3, UNSPECIFIED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcKnotType.htm
[ifcSql(TypeGroupId:4,TypeId:430397,TableId:4,LayerId:13)] public enum LaborResourceTypeEnum                {ADMINISTRATION=1, CARPENTRY=2, CLEANING=3, CONCRETE=4, DRYWALL=5, ELECTRIC=6, FINISHING=7, FLOORING=8, GENERAL=9, HVAC=10, LANDSCAPING=11, MASONRY=12, PAINTING=13, PAVING=14, PLUMBING=15, ROOFING=16, SITEGRADING=17, STEELWORK=18, SURVEYING=19, USERDEFINED=20, NOTDEFINED=21, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLaborResourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430398,TableId:4,LayerId:14)] public enum LampTypeEnum                         {COMPACTFLUORESCENT=1, FLUORESCENT=2, HALOGEN=3, HIGHPRESSUREMERCURY=4, HIGHPRESSURESODIUM=5, LED=6, METALHALIDE=7, OLED=8, TUNGSTENFILAMENT=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLampTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430399,TableId:4,LayerId:31)] public enum LayerSetDirectionEnum                {AXIS1=1, AXIS2=2, AXIS3=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLayerSetDirectionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430400,TableId:4,LayerId:35)] public enum LightDistributionCurveEnum           {TYPE_A=1, TYPE_B=2, TYPE_C=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLightDistributionCurveEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430401,TableId:4,LayerId:35)] public enum LightEmissionSourceEnum              {COMPACTFLUORESCENT=1, FLUORESCENT=2, HIGHPRESSUREMERCURY=3, HIGHPRESSURESODIUM=4, LIGHTEMITTINGDIODE=5, LOWPRESSURESODIUM=6, LOWVOLTAGEHALOGEN=7, MAINVOLTAGEHALOGEN=8, METALHALIDE=9, TUNGSTENFILAMENT=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLightEmissionSourceEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430402,TableId:4,LayerId:14)] public enum LightFixtureTypeEnum                 {DIRECTIONSOURCE=1, POINTSOURCE=2, SECURITYLIGHTING=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLightFixtureTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430403,TableId:4,LayerId:17)] public enum LiquidTerminalTypeEnum               {HOSEREEL=1, LOADINGARM=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLiquidTerminalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430404,TableId:4,LayerId:20)] public enum LoadGroupTypeEnum                    {LOAD_CASE=1, LOAD_COMBINATION=2, LOAD_GROUP=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLoadGroupTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430405,TableId:4,LayerId:24)] public enum LogicalOperatorEnum                  {LOGICALAND=1, LOGICALNOTAND=2, LOGICALNOTOR=3, LOGICALOR=4, LOGICALXOR=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcLogicalOperatorEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430406,TableId:4,LayerId:17)] public enum MarineFacilityTypeEnum               {BARRIERBEACH=1, BREAKWATER=2, CANAL=3, DRYDOCK=4, FLOATINGDOCK=5, HYDROLIFT=6, JETTY=7, LAUNCHRECOVERY=8, MARINEDEFENCE=9, NAVIGATIONALCHANNEL=10, PORT=11, QUAY=12, REVETMENT=13, SHIPLIFT=14, SHIPLOCK=15, SHIPYARD=16, SLIPWAY=17, WATERWAY=18, WATERWAYSHIPLIFT=19, USERDEFINED=20, NOTDEFINED=21, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMarineFacilityTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430407,TableId:4,LayerId:17)] public enum MarinePartTypeEnum                   {ABOVEWATERLINE=1, ANCHORAGE=2, APPROACHCHANNEL=3, BELOWWATERLINE=4, BERTHINGSTRUCTURE=5, CHAMBER=6, CILL_LEVEL=7, COPELEVEL=8, CORE=9, CREST=10, GATEHEAD=11, GUDINGSTRUCTURE=12, HIGHWATERLINE=13, LANDFIELD=14, LEEWARDSIDE=15, LOWWATERLINE=16, MANUFACTURING=17, NAVIGATIONALAREA=18, PROTECTION=19, SHIPTRANSFER=20, STORAGEAREA=21, VEHICLESERVICING=22, WATERFIELD=23, WEATHERSIDE=24, USERDEFINED=25, NOTDEFINED=26, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMarinePartTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430408,TableId:4,LayerId: 7)] public enum MechanicalFastenerTypeEnum           {ANCHORBOLT=1, BOLT=2, CHAIN=3, COUPLER=4, DOWEL=5, NAIL=6, NAILPLATE=7, RAILFASTENING=8, RAILJOINT=9, RIVET=10, ROPE=11, SCREW=12, SHEARCONNECTOR=13, STAPLE=14, STUDSHEARCONNECTOR=15, USERDEFINED=16, NOTDEFINED=17, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMechanicalFastenerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430409,TableId:4,LayerId:15)] public enum MedicalDeviceTypeEnum                {AIRSTATION=1, FEEDAIRUNIT=2, OXYGENGENERATOR=3, OXYGENPLANT=4, VACUUMSTATION=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMedicalDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430410,TableId:4,LayerId: 5)] public enum MemberTypeEnum                       {ARCH_SEGMENT=1, BRACE=2, CHORD=3, COLLAR=4, MEMBER=5, MULLION=6, PLATE=7, POST=8, PURLIN=9, RAFTER=10, STAY_CABLE=11, STIFFENING_RIB=12, STRINGER=13, STRUCTURALCABLE=14, STRUT=15, STUD=16, SUSPENDER=17, SUSPENSION_CABLE=18, TIEBAR=19, USERDEFINED=20, NOTDEFINED=21, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMemberTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430411,TableId:4,LayerId:18)] public enum MobileTelecommunicationsApplianceTypeEnum{ACCESSPOINT=1, BASEBANDUNIT=2, BASETRANSCEIVERSTATION=3, E_UTRAN_NODE_B=4, GATEWAY_GPRS_SUPPORT_NODE=5, MASTERUNIT=6, MOBILESWITCHINGCENTER=7, MSCSERVER=8, PACKETCONTROLUNIT=9, REMOTERADIOUNIT=10, REMOTEUNIT=11, SERVICE_GPRS_SUPPORT_NODE=12, SUBSCRIBERSERVER=13, USERDEFINED=14, NOTDEFINED=15, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMobileTelecommunicationsApplianceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430412,TableId:4,LayerId:17)] public enum MooringDeviceTypeEnum                {BOLLARD=1, LINETENSIONER=2, MAGNETICDEVICE=3, MOORINGHOOKS=4, VACUUMDEVICE=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMooringDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430413,TableId:4,LayerId:14)] public enum MotorConnectionTypeEnum              {BELTDRIVE=1, COUPLING=2, DIRECTDRIVE=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcMotorConnectionTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430414,TableId:4,LayerId:17)] public enum NavigationElementTypeEnum            {BEACON=1, BUOY=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcNavigationElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430415,TableId:4,LayerId:24)] public enum ObjectiveEnum                        {CODECOMPLIANCE=1, CODEWAIVER=2, DESIGNINTENT=3, EXTERNAL=4, HEALTHANDSAFETY=5, MERGECONFLICT=6, MODELVIEW=7, PARAMETER=8, REQUIREMENT=9, SPECIFICATION=10, TRIGGERCONDITION=11, USERDEFINED=12, NOTDEFINED=13, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcObjectiveEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430416,TableId:4,LayerId: 8)] public enum OccupantTypeEnum                     {ASSIGNEE=1, ASSIGNOR=2, LESSEE=3, LESSOR=4, LETTINGAGENT=5, OWNER=6, TENANT=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcOccupantTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430417,TableId:4,LayerId: 4)] public enum OpeningElementTypeEnum               {OPENING=1, RECESS=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcOpeningElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430418,TableId:4,LayerId:14)] public enum OutletTypeEnum                       {AUDIOVISUALOUTLET=1, COMMUNICATIONSOUTLET=2, DATAOUTLET=3, POWEROUTLET=4, TELEPHONEOUTLET=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcOutletTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430419,TableId:4,LayerId: 9)] public enum PavementTypeEnum                     {FLEXIBLE=1, RIGID=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPavementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430420,TableId:4,LayerId: 1)] public enum PerformanceHistoryTypeEnum           {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPerformanceHistoryTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430421,TableId:4,LayerId:11)] public enum PermeableCoveringOperationEnum       {GRILL=1, LOUVER=2, SCREEN=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPermeableCoveringOperationEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430422,TableId:4,LayerId:10)] public enum PermitTypeEnum                       {ACCESS=1, BUILDING=2, WORK=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPermitTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430423,TableId:4,LayerId: 4)] public enum PhysicalOrVirtualEnum                {PHYSICAL=1, VIRTUAL=2, NOTDEFINED=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPhysicalOrVirtualEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430424,TableId:4,LayerId:21)] public enum PileConstructionEnum                 {CAST_IN_PLACE=1, COMPOSITE=2, PRECAST_CONCRETE=3, PREFAB_STEEL=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPileConstructionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430425,TableId:4,LayerId:21)] public enum PileTypeEnum                         {BORED=1, COHESION=2, DRIVEN=3, FRICTION=4, JETGROUTING=5, SUPPORT=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPileTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430426,TableId:4,LayerId:15)] public enum PipeFittingTypeEnum                  {BEND=1, CONNECTOR=2, ENTRY=3, EXIT=4, JUNCTION=5, OBSTRUCTION=6, TRANSITION=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPipeFittingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430427,TableId:4,LayerId:15)] public enum PipeSegmentTypeEnum                  {CULVERT=1, FLEXIBLESEGMENT=2, GUTTER=3, RIGIDSEGMENT=4, SPOOL=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPipeSegmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430428,TableId:4,LayerId: 5)] public enum PlateTypeEnum                        {BASE_PLATE=1, COVER_PLATE=2, CURTAIN_PANEL=3, FLANGE_PLATE=4, GUSSET_PLATE=5, SHEET=6, SPLICE_PLATE=7, STIFFENER_PLATE=8, WEB_PLATE=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPlateTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430429,TableId:4,LayerId:30)] public enum PreferredSurfaceCurveRepresentation  {CURVE3D=1, PCURVE_S1=2, PCURVE_S2=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPreferredSurfaceCurveRepresentation.htm
[ifcSql(TypeGroupId:4,TypeId:430430,TableId:4,LayerId: 3)] public enum ProcedureTypeEnum                    {ADVICE_CAUTION=1, ADVICE_NOTE=2, ADVICE_WARNING=3, CALIBRATION=4, DIAGNOSTIC=5, SHUTDOWN=6, STARTUP=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProcedureTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430431,TableId:4,LayerId:36)] public enum ProfileTypeEnum                      {AREA=1, CURVE=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProfileTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430432,TableId:4,LayerId:10)] public enum ProjectOrderTypeEnum                 {CHANGEORDER=1, MAINTENANCEWORKORDER=2, MOVEORDER=3, PURCHASEORDER=4, WORKORDER=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProjectOrderTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430433,TableId:4,LayerId:20)] public enum ProjectedOrTrueLengthEnum            {PROJECTED_LENGTH=1, TRUE_LENGTH=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProjectedOrTrueLengthEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430434,TableId:4,LayerId: 4)] public enum ProjectionElementTypeEnum            {BLISTER=1, DEVIATOR=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProjectionElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430435,TableId:4,LayerId: 2)] public enum PropertySetTemplateTypeEnum          {PSET_MATERIALDRIVEN=1, PSET_OCCURRENCEDRIVEN=2, PSET_PERFORMANCEDRIVEN=3, PSET_PROFILEDRIVEN=4, PSET_TYPEDRIVENONLY=5, PSET_TYPEDRIVENOVERRIDE=6, QTO_OCCURRENCEDRIVEN=7, QTO_TYPEDRIVENONLY=8, QTO_TYPEDRIVENOVERRIDE=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPropertySetTemplateTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430436,TableId:4,LayerId:14)] public enum ProtectiveDeviceTrippingUnitTypeEnum {ELECTROMAGNETIC=1, ELECTRONIC=2, RESIDUALCURRENT=3, THERMAL=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProtectiveDeviceTrippingUnitTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430437,TableId:4,LayerId:14)] public enum ProtectiveDeviceTypeEnum             {ANTI_ARCING_DEVICE=1, CIRCUITBREAKER=2, EARTHINGSWITCH=3, EARTHLEAKAGECIRCUITBREAKER=4, FUSEDISCONNECTOR=5, RESIDUALCURRENTCIRCUITBREAKER=6, RESIDUALCURRENTSWITCH=7, SPARKGAP=8, VARISTOR=9, VOLTAGELIMITER=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcProtectiveDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430438,TableId:4,LayerId:15)] public enum PumpTypeEnum                         {CIRCULATOR=1, ENDSUCTION=2, SPLITCASE=3, SUBMERSIBLEPUMP=4, SUMPPUMP=5, VERTICALINLINE=6, VERTICALTURBINE=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcPumpTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430439,TableId:4,LayerId:18)] public enum RailTypeEnum                         {BLADE=1, CHECKRAIL=2, GUARDRAIL=3, RACKRAIL=4, RAIL=5, STOCKRAIL=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRailTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430440,TableId:4,LayerId: 5)] public enum RailingTypeEnum                      {BALUSTRADE=1, FENCE=2, GUARDRAIL=3, HANDRAIL=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRailingTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430441,TableId:4,LayerId:18)] public enum RailwayPartTypeEnum                  {ABOVETRACK=1, DILATIONTRACK=2, LINESIDE=3, LINESIDEPART=4, PLAINTRACK=5, SUBSTRUCTURE=6, TRACK=7, TRACKPART=8, TURNOUTTRACK=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRailwayPartTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430442,TableId:4,LayerId: 5)] public enum RailwayTypeEnum                      {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRailwayTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430443,TableId:4,LayerId: 5)] public enum RampFlightTypeEnum                   {SPIRAL=1, STRAIGHT=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRampFlightTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430444,TableId:4,LayerId: 5)] public enum RampTypeEnum                         {HALF_TURN_RAMP=1, QUARTER_TURN_RAMP=2, SPIRAL_RAMP=3, STRAIGHT_RUN_RAMP=4, TWO_QUARTER_TURN_RAMP=5, TWO_STRAIGHT_RUN_RAMP=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRampTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430445,TableId:4,LayerId:26)] public enum RecurrenceTypeEnum                   {BY_DAY_COUNT=1, BY_WEEKDAY_COUNT=2, DAILY=3, MONTHLY_BY_DAY_OF_MONTH=4, MONTHLY_BY_POSITION=5, WEEKLY=6, YEARLY_BY_DAY_OF_MONTH=7, YEARLY_BY_POSITION=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRecurrenceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430446,TableId:4,LayerId: 4)] public enum ReferentTypeEnum                     {BOUNDARY=1, INTERSECTION=2, KILOPOINT=3, LANDMARK=4, MILEPOINT=5, POSITION=6, REFERENCEMARKER=7, STATION=8, SUPERELEVATIONEVENT=9, WIDTHEVENT=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReferentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430447,TableId:4,LayerId:33)] public enum ReflectanceMethodEnum                {BLINN=1, FLAT=2, GLASS=3, MATT=4, METAL=5, MIRROR=6, PHONG=7, PHYSICAL=8, PLASTIC=9, STRAUSS=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReflectanceMethodEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430448,TableId:4,LayerId: 9)] public enum ReinforcedSoilTypeEnum               {DYNAMICALLYCOMPACTED=1, GROUTED=2, REPLACED=3, ROLLERCOMPACTED=4, SURCHARGEPRELOADED=5, VERTICALLYDRAINED=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReinforcedSoilTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430449,TableId:4,LayerId:36)] public enum ReinforcingBarRoleEnum               {ANCHORING=1, EDGE=2, LIGATURE=3, MAIN=4, PUNCHING=5, RING=6, SHEAR=7, STUD=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReinforcingBarRoleEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430450,TableId:4,LayerId:36)] public enum ReinforcingBarSurfaceEnum            {PLAIN=1, TEXTURED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReinforcingBarSurfaceEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430451,TableId:4,LayerId:21)] public enum ReinforcingBarTypeEnum               {ANCHORING=1, EDGE=2, LIGATURE=3, MAIN=4, PUNCHING=5, RING=6, SHEAR=7, SPACEBAR=8, STUD=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReinforcingBarTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430452,TableId:4,LayerId:21)] public enum ReinforcingMeshTypeEnum              {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcReinforcingMeshTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430453,TableId:4,LayerId:19)] public enum RoadPartTypeEnum                     {BICYCLECROSSING=1, BUS_STOP=2, CARRIAGEWAY=3, CENTRALISLAND=4, CENTRALRESERVE=5, HARDSHOULDER=6, INTERSECTION=7, LAYBY=8, PARKINGBAY=9, PASSINGBAY=10, PEDESTRIAN_CROSSING=11, RAILWAYCROSSING=12, REFUGEISLAND=13, ROADSEGMENT=14, ROADSIDE=15, ROADSIDEPART=16, ROADWAYPLATEAU=17, ROUNDABOUT=18, SHOULDER=19, SIDEWALK=20, SOFTSHOULDER=21, TOLLPLAZA=22, TRAFFICISLAND=23, TRAFFICLANE=24, USERDEFINED=25, NOTDEFINED=26, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRoadPartTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430454,TableId:4,LayerId:32)] public enum RoadTypeEnum                         {USERDEFINED=1, NOTDEFINED=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRoadTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430455,TableId:4,LayerId:22)] public enum RoleEnum                             {ARCHITECT=1, BUILDINGOPERATOR=2, BUILDINGOWNER=3, CIVILENGINEER=4, CLIENT=5, COMMISSIONINGENGINEER=6, CONSTRUCTIONMANAGER=7, CONSULTANT=8, CONTRACTOR=9, COSTENGINEER=10, ELECTRICALENGINEER=11, ENGINEER=12, FACILITIESMANAGER=13, FIELDCONSTRUCTIONMANAGER=14, MANUFACTURER=15, MECHANICALENGINEER=16, OWNER=17, PROJECTMANAGER=18, RESELLER=19, STRUCTURALENGINEER=20, SUBCONTRACTOR=21, SUPPLIER=22, USERDEFINED=23, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRoleEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430456,TableId:4,LayerId: 5)] public enum RoofTypeEnum                         {BARREL_ROOF=1, BUTTERFLY_ROOF=2, DOME_ROOF=3, FLAT_ROOF=4, FREEFORM=5, GABLE_ROOF=6, GAMBREL_ROOF=7, HIPPED_GABLE_ROOF=8, HIP_ROOF=9, MANSARD_ROOF=10, PAVILION_ROOF=11, RAINBOW_ROOF=12, SHED_ROOF=13, USERDEFINED=14, NOTDEFINED=15, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcRoofTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430457,TableId:4,LayerId:32)] public enum SIPrefix                             {ATTO=1, CENTI=2, DECA=3, DECI=4, EXA=5, FEMTO=6, GIGA=7, HECTO=8, KILO=9, MEGA=10, MICRO=11, MILLI=12, NANO=13, PETA=14, PICO=15, TERA=16, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSIPrefix.htm
[ifcSql(TypeGroupId:4,TypeId:430458,TableId:4,LayerId:32)] public enum SIUnitName                           {AMPERE=1, BECQUEREL=2, CANDELA=3, COULOMB=4, CUBIC_METRE=5, DEGREE_CELSIUS=6, FARAD=7, GRAM=8, GRAY=9, HENRY=10, HERTZ=11, JOULE=12, KELVIN=13, LUMEN=14, LUX=15, METRE=16, MOLE=17, NEWTON=18, OHM=19, PASCAL=20, RADIAN=21, SECOND=22, SIEMENS=23, SIEVERT=24, SQUARE_METRE=25, STERADIAN=26, TESLA=27, VOLT=28, WATT=29, WEBER=30, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSIUnitName.htm
[ifcSql(TypeGroupId:4,TypeId:430459,TableId:4,LayerId:16)] public enum SanitaryTerminalTypeEnum             {BATH=1, BIDET=2, CISTERN=3, SANITARYFOUNTAIN=4, SHOWER=5, SINK=6, TOILETPAN=7, URINAL=8, WASHHANDBASIN=9, WCSEAT=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSanitaryTerminalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430460,TableId:4,LayerId:36)] public enum SectionTypeEnum                      {TAPERED=1, UNIFORM=2, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSectionTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430461,TableId:4,LayerId:12)] public enum SensorTypeEnum                       {CO2SENSOR=1, CONDUCTANCESENSOR=2, CONTACTSENSOR=3, COSENSOR=4, EARTHQUAKESENSOR=5, FIRESENSOR=6, FLOWSENSOR=7, FOREIGNOBJECTDETECTIONSENSOR=8, FROSTSENSOR=9, GASSENSOR=10, HEATSENSOR=11, HUMIDITYSENSOR=12, IDENTIFIERSENSOR=13, IONCONCENTRATIONSENSOR=14, LEVELSENSOR=15, LIGHTSENSOR=16, MOISTURESENSOR=17, MOVEMENTSENSOR=18, OBSTACLESENSOR=19, PHSENSOR=20, PRESSURESENSOR=21, RADIATIONSENSOR=22, RADIOACTIVITYSENSOR=23, RAINSENSOR=24, SMOKESENSOR=25, SNOWDEPTHSENSOR=26, SOUNDSENSOR=27, TEMPERATURESENSOR=28, TRAINSENSOR=29, TURNOUTCLOSURESENSOR=30, WHEELSENSOR=31, WINDSENSOR=32, USERDEFINED=33, NOTDEFINED=34, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSensorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430462,TableId:4,LayerId: 3)] public enum SequenceEnum                         {FINISH_FINISH=1, FINISH_START=2, START_FINISH=3, START_START=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSequenceEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430463,TableId:4,LayerId: 5)] public enum ShadingDeviceTypeEnum                {AWNING=1, JALOUSIE=2, SHUTTER=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcShadingDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430464,TableId:4,LayerId: 9)] public enum SignTypeEnum                         {MARKER=1, MIRROR=2, PICTORAL=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSignTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430465,TableId:4,LayerId: 9)] public enum SignalTypeEnum                       {AUDIO=1, MIXED=2, VISUAL=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSignalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430466,TableId:4,LayerId: 2)] public enum SimplePropertyTemplateTypeEnum       {P_BOUNDEDVALUE=1, P_ENUMERATEDVALUE=2, P_LISTVALUE=3, P_REFERENCEVALUE=4, P_SINGLEVALUE=5, P_TABLEVALUE=6, Q_AREA=7, Q_COUNT=8, Q_LENGTH=9, Q_NUMBER=10, Q_TIME=11, Q_VOLUME=12, Q_WEIGHT=13, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSimplePropertyTemplateTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430467,TableId:4,LayerId: 5)] public enum SlabTypeEnum                         {APPROACH_SLAB=1, BASESLAB=2, FLOOR=3, LANDING=4, PAVING=5, ROOF=6, SIDEWALK=7, TRACKSLAB=8, WEARING=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSlabTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430468,TableId:4,LayerId:14)] public enum SolarDeviceTypeEnum                  {SOLARCOLLECTOR=1, SOLARPANEL=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSolarDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430469,TableId:4,LayerId:15)] public enum SpaceHeaterTypeEnum                  {CONVECTOR=1, RADIATOR=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSpaceHeaterTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430470,TableId:4,LayerId: 4)] public enum SpaceTypeEnum                        {BERTH=1, EXTERNAL=2, GFA=3, INTERNAL=4, PARKING=5, SPACE=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSpaceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430471,TableId:4,LayerId: 4)] public enum SpatialZoneTypeEnum                  {CONSTRUCTION=1, FIRESAFETY=2, INTERFERENCE=3, LIGHTING=4, OCCUPANCY=5, RESERVATION=6, SECURITY=7, THERMAL=8, TRANSPORT=9, VENTILATION=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSpatialZoneTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430472,TableId:4,LayerId:16)] public enum StackTerminalTypeEnum                {BIRDCAGE=1, COWL=2, RAINWATERHOPPER=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStackTerminalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430473,TableId:4,LayerId: 5)] public enum StairFlightTypeEnum                  {CURVED=1, FREEFORM=2, SPIRAL=3, STRAIGHT=4, WINDER=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStairFlightTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430474,TableId:4,LayerId: 5)] public enum StairTypeEnum                        {CURVED_RUN_STAIR=1, DOUBLE_RETURN_STAIR=2, HALF_TURN_STAIR=3, HALF_WINDING_STAIR=4, LADDER=5, QUARTER_TURN_STAIR=6, QUARTER_WINDING_STAIR=7, SPIRAL_STAIR=8, STRAIGHT_RUN_STAIR=9, THREE_QUARTER_TURN_STAIR=10, THREE_QUARTER_WINDING_STAIR=11, TWO_CURVED_RUN_STAIR=12, TWO_QUARTER_TURN_STAIR=13, TWO_QUARTER_WINDING_STAIR=14, TWO_STRAIGHT_RUN_STAIR=15, USERDEFINED=16, NOTDEFINED=17, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStairTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430475,TableId:4,LayerId:42)] public enum StateEnum                            {LOCKED=1, READONLY=2, READONLYLOCKED=3, READWRITE=4, READWRITELOCKED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStateEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430476,TableId:4,LayerId:20)] public enum StructuralCurveActivityTypeEnum      {CONST=1, DISCRETE=2, EQUIDISTANT=3, LINEAR=4, PARABOLA=5, POLYGONAL=6, SINUS=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStructuralCurveActivityTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430477,TableId:4,LayerId:20)] public enum StructuralCurveMemberTypeEnum        {CABLE=1, COMPRESSION_MEMBER=2, PIN_JOINED_MEMBER=3, RIGID_JOINED_MEMBER=4, TENSION_MEMBER=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStructuralCurveMemberTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430478,TableId:4,LayerId:20)] public enum StructuralSurfaceActivityTypeEnum    {BILINEAR=1, CONST=2, DISCRETE=3, ISOCONTOUR=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStructuralSurfaceActivityTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430479,TableId:4,LayerId:20)] public enum StructuralSurfaceMemberTypeEnum      {BENDING_ELEMENT=1, MEMBRANE_ELEMENT=2, SHELL=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcStructuralSurfaceMemberTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430480,TableId:4,LayerId:13)] public enum SubContractResourceTypeEnum          {PURCHASE=1, WORK=2, USERDEFINED=3, NOTDEFINED=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSubContractResourceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430481,TableId:4,LayerId:21)] public enum SurfaceFeatureTypeEnum               {DEFECT=1, HATCHMARKING=2, LINEMARKING=3, MARK=4, NONSKIDSURFACING=5, PAVEMENTSURFACEMARKING=6, RUMBLESTRIP=7, SYMBOLMARKING=8, TAG=9, TRANSVERSERUMBLESTRIP=10, TREATMENT=11, USERDEFINED=12, NOTDEFINED=13, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSurfaceFeatureTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430482,TableId:4,LayerId:33)] public enum SurfaceSide                          {BOTH=1, NEGATIVE=2, POSITIVE=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSurfaceSide.htm
[ifcSql(TypeGroupId:4,TypeId:430483,TableId:4,LayerId:14)] public enum SwitchingDeviceTypeEnum              {CONTACTOR=1, DIMMERSWITCH=2, EMERGENCYSTOP=3, KEYPAD=4, MOMENTARYSWITCH=5, RELAY=6, SELECTORSWITCH=7, STARTER=8, START_AND_STOP_EQUIPMENT=9, SWITCHDISCONNECTOR=10, TOGGLESWITCH=11, USERDEFINED=12, NOTDEFINED=13, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSwitchingDeviceTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430484,TableId:4,LayerId: 8)] public enum SystemFurnitureElementTypeEnum       {PANEL=1, SUBRACK=2, WORKSURFACE=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcSystemFurnitureElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430485,TableId:4,LayerId:15)] public enum TankTypeEnum                         {BASIN=1, BREAKPRESSURE=2, EXPANSION=3, FEEDANDEXPANSION=4, OILRETENTIONTRAY=5, PRESSUREVESSEL=6, STORAGE=7, VESSEL=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTankTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430486,TableId:4,LayerId:26)] public enum TaskDurationEnum                     {ELAPSEDTIME=1, WORKTIME=2, NOTDEFINED=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTaskDurationEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430487,TableId:4,LayerId: 3)] public enum TaskTypeEnum                         {ADJUSTMENT=1, ATTENDANCE=2, CALIBRATION=3, CONSTRUCTION=4, DEMOLITION=5, DISMANTLE=6, DISPOSAL=7, EMERGENCY=8, INSPECTION=9, INSTALLATION=10, LOGISTIC=11, MAINTENANCE=12, MOVE=13, OPERATION=14, REMOVAL=15, RENOVATION=16, SAFETY=17, SHUTDOWN=18, STARTUP=19, TESTING=20, TROUBLESHOOTING=21, USERDEFINED=22, NOTDEFINED=23, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTaskTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430488,TableId:4,LayerId:21)] public enum TendonAnchorTypeEnum                 {COUPLER=1, FIXED_END=2, TENSIONING_END=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTendonAnchorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430489,TableId:4,LayerId:21)] public enum TendonConduitTypeEnum                {COUPLER=1, DIABOLO=2, DUCT=3, GROUTING_DUCT=4, TRUMPET=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTendonConduitTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430490,TableId:4,LayerId:21)] public enum TendonTypeEnum                       {BAR=1, COATED=2, STRAND=3, WIRE=4, USERDEFINED=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTendonTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430491,TableId:4,LayerId:34)] public enum TextPath                             {DOWN=1, LEFT=2, RIGHT=3, UP=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTextPath.htm
[ifcSql(TypeGroupId:4,TypeId:430492,TableId:4,LayerId:26)] public enum TimeSeriesDataTypeEnum               {CONTINUOUS=1, DISCRETE=2, DISCRETEBINARY=3, PIECEWISEBINARY=4, PIECEWISECONSTANT=5, PIECEWISECONTINUOUS=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTimeSeriesDataTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430493,TableId:4,LayerId:18)] public enum TrackElementTypeEnum                 {BLOCKINGDEVICE=1, DERAILER=2, FROG=3, HALF_SET_OF_BLADES=4, SLEEPER=5, SPEEDREGULATOR=6, TRACKENDOFALIGNMENT=7, VEHICLESTOP=8, USERDEFINED=9, NOTDEFINED=10, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTrackElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430494,TableId:4,LayerId:14)] public enum TransformerTypeEnum                  {CHOPPER=1, COMBINED=2, CURRENT=3, FREQUENCY=4, INVERTER=5, RECTIFIER=6, VOLTAGE=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTransformerTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430495,TableId:4,LayerId:30)] public enum TransitionCode                       {CONTINUOUS=1, CONTSAMEGRADIENT=2, CONTSAMEGRADIENTSAMECURVATURE=3, DISCONTINUOUS=4, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTransitionCode.htm
[ifcSql(TypeGroupId:4,TypeId:430496,TableId:4,LayerId: 4)] public enum TransportElementTypeEnum             {CRANEWAY=1, ELEVATOR=2, ESCALATOR=3, HAULINGGEAR=4, LIFTINGGEAR=5, MOVINGWALKWAY=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTransportElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430497,TableId:4,LayerId:30)] public enum TrimmingPreference                   {CARTESIAN=1, PARAMETER=2, UNSPECIFIED=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTrimmingPreference.htm
[ifcSql(TypeGroupId:4,TypeId:430498,TableId:4,LayerId:15)] public enum TubeBundleTypeEnum                   {FINNED=1, USERDEFINED=2, NOTDEFINED=3, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcTubeBundleTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430499,TableId:4,LayerId:32)] public enum UnitEnum                             {ABSORBEDDOSEUNIT=1, AMOUNTOFSUBSTANCEUNIT=2, AREAUNIT=3, DOSEEQUIVALENTUNIT=4, ELECTRICCAPACITANCEUNIT=5, ELECTRICCHARGEUNIT=6, ELECTRICCONDUCTANCEUNIT=7, ELECTRICCURRENTUNIT=8, ELECTRICRESISTANCEUNIT=9, ELECTRICVOLTAGEUNIT=10, ENERGYUNIT=11, FORCEUNIT=12, FREQUENCYUNIT=13, ILLUMINANCEUNIT=14, INDUCTANCEUNIT=15, LENGTHUNIT=16, LUMINOUSFLUXUNIT=17, LUMINOUSINTENSITYUNIT=18, MAGNETICFLUXDENSITYUNIT=19, MAGNETICFLUXUNIT=20, MASSUNIT=21, PLANEANGLEUNIT=22, POWERUNIT=23, PRESSUREUNIT=24, RADIOACTIVITYUNIT=25, SOLIDANGLEUNIT=26, THERMODYNAMICTEMPERATUREUNIT=27, TIMEUNIT=28, VOLUMEUNIT=29, USERDEFINED=30, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcUnitEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430500,TableId:4,LayerId:12)] public enum UnitaryControlElementTypeEnum        {ALARMPANEL=1, BASESTATIONCONTROLLER=2, COMBINED=3, CONTROLPANEL=4, GASDETECTIONPANEL=5, HUMIDISTAT=6, INDICATORPANEL=7, MIMICPANEL=8, THERMOSTAT=9, WEATHERSTATION=10, USERDEFINED=11, NOTDEFINED=12, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcUnitaryControlElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430501,TableId:4,LayerId:15)] public enum UnitaryEquipmentTypeEnum             {AIRCONDITIONINGUNIT=1, AIRHANDLER=2, DEHUMIDIFIER=3, ROOFTOPUNIT=4, SPLITSYSTEM=5, USERDEFINED=6, NOTDEFINED=7, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcUnitaryEquipmentTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430502,TableId:4,LayerId:15)] public enum ValveTypeEnum                        {AIRRELEASE=1, ANTIVACUUM=2, CHANGEOVER=3, CHECK=4, COMMISSIONING=5, DIVERTING=6, DOUBLECHECK=7, DOUBLEREGULATING=8, DRAWOFFCOCK=9, FAUCET=10, FLUSHING=11, GASCOCK=12, GASTAP=13, ISOLATING=14, MIXING=15, PRESSUREREDUCING=16, PRESSURERELIEF=17, REGULATING=18, SAFETYCUTOFF=19, STEAMTRAP=20, STOPCOCK=21, USERDEFINED=22, NOTDEFINED=23, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcValveTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430503,TableId:4,LayerId: 4)] public enum VehicleTypeEnum                      {CARGO=1, ROLLINGSTOCK=2, VEHICLE=3, VEHICLEAIR=4, VEHICLEMARINE=5, VEHICLETRACKED=6, VEHICLEWHEELED=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcVehicleTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430504,TableId:4,LayerId: 7)] public enum VibrationDamperTypeEnum              {AXIAL_YIELD=1, BENDING_YIELD=2, FRICTION=3, RUBBER=4, SHEAR_YIELD=5, VISCOUS=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcVibrationDamperTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430505,TableId:4,LayerId:15)] public enum VibrationIsolatorTypeEnum            {BASE=1, COMPRESSION=2, SPRING=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcVibrationIsolatorTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430506,TableId:4,LayerId: 4)] public enum VirtualElementTypeEnum               {BOUNDARY=1, CLEARANCE=2, PROVISIONFORVOID=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcVirtualElementTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430507,TableId:4,LayerId:21)] public enum VoidingFeatureTypeEnum               {CHAMFER=1, CUTOUT=2, EDGE=3, HOLE=4, MITER=5, NOTCH=6, USERDEFINED=7, NOTDEFINED=8, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcVoidingFeatureTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430508,TableId:4,LayerId: 5)] public enum WallTypeEnum                         {ELEMENTEDWALL=1, MOVABLE=2, PARAPET=3, PARTITIONING=4, PLUMBINGWALL=5, POLYGONAL=6, RETAININGWALL=7, SHEAR=8, SOLIDWALL=9, STANDARD=10, WAVEWALL=11, USERDEFINED=12, NOTDEFINED=13, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWallTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430509,TableId:4,LayerId:16)] public enum WasteTerminalTypeEnum                {FLOORTRAP=1, FLOORWASTE=2, GULLYSUMP=3, GULLYTRAP=4, ROOFDRAIN=5, WASTEDISPOSALUNIT=6, WASTETRAP=7, USERDEFINED=8, NOTDEFINED=9, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWasteTerminalTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430510,TableId:4,LayerId:11)] public enum WindowPanelOperationEnum             {BOTTOMHUNG=1, FIXEDCASEMENT=2, OTHEROPERATION=3, PIVOTHORIZONTAL=4, PIVOTVERTICAL=5, REMOVABLECASEMENT=6, SIDEHUNGLEFTHAND=7, SIDEHUNGRIGHTHAND=8, SLIDINGHORIZONTAL=9, SLIDINGVERTICAL=10, TILTANDTURNLEFTHAND=11, TILTANDTURNRIGHTHAND=12, TOPHUNG=13, NOTDEFINED=14, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWindowPanelOperationEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430511,TableId:4,LayerId:11)] public enum WindowPanelPositionEnum              {BOTTOM=1, LEFT=2, MIDDLE=3, RIGHT=4, TOP=5, NOTDEFINED=6, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWindowPanelPositionEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430512,TableId:4,LayerId: 5)] public enum WindowTypeEnum                       {LIGHTDOME=1, SKYLIGHT=2, WINDOW=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWindowTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430513,TableId:4,LayerId: 5)] public enum WindowTypePartitioningEnum           {DOUBLE_PANEL_HORIZONTAL=1, DOUBLE_PANEL_VERTICAL=2, SINGLE_PANEL=3, TRIPLE_PANEL_BOTTOM=4, TRIPLE_PANEL_HORIZONTAL=5, TRIPLE_PANEL_LEFT=6, TRIPLE_PANEL_RIGHT=7, TRIPLE_PANEL_TOP=8, TRIPLE_PANEL_VERTICAL=9, USERDEFINED=10, NOTDEFINED=11, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWindowTypePartitioningEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430514,TableId:4,LayerId: 3)] public enum WorkCalendarTypeEnum                 {FIRSTSHIFT=1, SECONDSHIFT=2, THIRDSHIFT=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWorkCalendarTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430515,TableId:4,LayerId: 3)] public enum WorkPlanTypeEnum                     {ACTUAL=1, BASELINE=2, PLANNED=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWorkPlanTypeEnum.htm
[ifcSql(TypeGroupId:4,TypeId:430516,TableId:4,LayerId: 3)] public enum WorkScheduleTypeEnum                 {ACTUAL=1, BASELINE=2, PLANNED=3, USERDEFINED=4, NOTDEFINED=5, }// https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/index.html/HTML/lexical/IfcWorkScheduleTypeEnum.htm

}// of ifc #############################################################################################################
